name: Publish to npm

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    uses: CubytsAS/.github/.github/workflows/npm-publish.yml@main
    secrets: inherit
